(function () {
    "use strict";

    var categoryArray = [
    { title: "mieso i wedliny", picture: "images/miecho.jpg", id: 1 },
    { title: "ryby i owoce morza", picture: "images/ryba.jpg", id: 2 },
    { title: "nabial", picture: "images/nabial.jpg", id: 3 },
    { title: "warzywa", picture: "images/warzywa.jpg", id: 4 },
    { title: "owoce", picture: "images/owoce.jpg", id: 5 },
    { title: "pieczywo", picture: "images/pieczywo.jpg", id: 6 },
    { title: "grzyby", picture: "images/grzyby.jpg", id: 7 },
    { title: "zupy", picture: "images/soup.jpg", id: 8 },
    { title: "sosy", picture: "images/sos.jpg", id: 9 },
    { title: "przetwory", picture: "images/przetwory.jpg", id: 10 },
    { title: "desery", picture: "images/deser.jpg", id: 11 },
    { title: "napoje", picture: "images/napoj.jpg", id: 12 },
    { title: "salatki", picture: "images/salatka.jpg", id: 13 },
    { title: "studenckie", picture: "images/studenckie.jpg", id: 14 }
    ];

    var ingridientArray = [
        { name: 'mąka', id: 1 },
        { name: 'drożdże', id: 2 },
        { name: 'woda', id: 3 },
        { name: 'olej', id: 4 },
        { name: 'sól', id: 5 },
        { name: 'oliwki w plastrach', id: 6 },
        { name: 'brokuły', id: 7 },
        { name: 'czerwona ostra papryka', id: 8 },
        { name: 'pieczarki', id: 9 },
        { name: 'ser żółty', id: 10 },
        { name: 'ser biały', id: 11 },
        { name: 'cukier', id: 12 },
        { name: 'jajka', id: 13 },
        { name: 'masło', id: 14 },
        { name: 'kasza manna', id: 15 },
        { name: 'budyń waniliowy', id: 16 },
        { name: 'śmietana kremówka 30%', id: 17 },
        { name: 'olejek waniliowy', id: 18 },
        { name: 'tuńczyk', id: 19 },
        { name: 'kukurydza', id: 20 },
        { name: 'cebula', id: 21 },
        { name: 'majonez', id: 22 },
        { name: 'pieprz', id: 23 },
        { name: 'czerwone wino', id: 24 },
        { name: 'pomarańcza', id: 25 },
        { name: 'gożdziki', id: 26 },
        { name: 'cynamon', id: 27 },
        { name: 'plasterki limonki', id: 28 },
        { name: 'syrop malinowy', id: 29 },
        { name: 'miód', id: 30 },
        { name: 'grzanki', id: 31 },
        { name: 'jajka ugotowane na miękko', id: 32 },
        { name: 'szynka plasterki', id: 33 },
        { name: 'ser pleśniowy plasterki', id: 34 },
        { name: 'ser topiony z papryką plasterki', id: 35 },
        { name: 'chrzan', id: 36 },
        { name: 'czarna cherbata z sokiem malinowym', id: 37 },
        { name: 'kasza jaglana', id: 38 },
        { name: 'słonecznik', id: 39 },
        { name: 'bułka tarta', id: 40 },
        { name: 'oliwa z oliwek', id: 41 },
        { name: 'jogurt naturalny', id: 42 },
        { name: 'koperek', id: 43 },
        { name: 'czosnek', id: 44 },
        { name: 'ogórek konserwowy', id: 45 },
        { name: 'szynka wieprzowa', id: 46 },
        { name: 'pieprz kolorowy', id: 48 },
        { name: 'czosnek granulowany', id: 49 },
        { name: 'ostra papryka w proszku', id: 50 },
        { name: 'magi', id: 51 },
        { name: 'marchew', id: 52 },
        { name: 'cynamon', id: 53 },
        { name: 'otręby owsiane', id: 54 },
        { name: 'proszek do pieczenie', id: 55 },
        { name: 'rodzynki', id: 56 },
        { name: 'słodzik w proszku', id: 57 },
        { name: 'plastry boczku', id: 58 },
        { name: 'budyń śmietankowy', id: 62 },
        { name: 'grysik', id: 64 },
        { name: 'mleko', id: 65 },
        { name: 'margaryna', id: 66 },
        { name: 'cukier puder', id: 68 },
        { name: 'adwokat', id: 69 },
        { name: 'owoce', id: 70 },
        { name: 'mąka tortowa', id: 71 },
        { name: 'płatki żytnie', id: 73 },
        { name: 'siemie lniane', id: 75 },
        { name: 'zakwas żytni', id: 76 },
        { name: 'miód', id: 78 },
        { name: 'mąka żytnia', id: 79 },
        { name: 'mąka pszenna', id: 80 },
        { name: 'melon', id: 81 },
        { name: 'oliwki czarne', id: 82 },
        { name: 'oliwki zielone', id: 83 },
        { name: 'rzodkiewki', id: 84 },
        { name: 'kabanos', id: 85 },
        { name: 'papryka konserwowa', id: 86 },
        { name: 'pomidory koktajlowe', id: 88 },
        { name: 'wykałaczki', id: 89 },
        { name: 'serek mascarpone', id: 90 },
        { name: 'mleko skondensowane', id: 91 },
        { name: 'sok z cytryny', id: 92 },
        { name: 'ciasteczka bee-bee', id: 94 },
        { name: 'biszkopt', id: 95 },
        { name: 'mąka ziemniaczana', id: 98 },
        { name: 'cytryna', id: 99 },
        { name: 'jabłka', id: 100 },
        { name: 'orzechy włoskie', id: 101 },
        { name: 'gorzka czekolada', id: 102 },
        { name: 'mleczna czekolada', id: 103 },
        { name: 'olejek waniliowy', id: 104 },
        { name: 'mięso mielone', id: 106 },
        { name: 'fasola czerwona', id: 107 },
        { name: 'papryka czerwona', id: 108 },
        { name: 'pomidory bez skórek', id: 109 },
        { name: 'przyprawy', id: 110 },
        { name: 'truskawki', id: 111 },
        { name: 'ser feta', id: 113 },
        { name: 'sałata lodowa', id: 115 },
        { name: 'ogórek zielony', id: 116 },
        { name: 'mozzarella', id: 117 },
        { name: 'przyprawa winegrete', id: 118 },
        { name: 'laska wanilli', id: 121 },
        { name: 'migdały', id: 123 }
    ];

    var cat = new WinJS.Binding.List(categoryArray);
    var ing = new WinJS.Binding.List(ingridientArray);
  
    var publicMembers =
        {
            catList: cat,
            ingList: ing
        };
    WinJS.Namespace.define("DataExample", publicMembers);
})();